version: "3"
services:
  web:
    image: keozon/basic-stats:v1
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:8080"
    networks:
      - webnet
networks:
  webnet:
